questions:
  - question_id: "q1"
    text: "Пожалуйста, отметьте те варианты и средства коммуникации, которые Вы используете достаточно часто в своей жизни"
    type: "multi-choice"
    options:
      - id: "1.1"
        text: "Кнопочный телефон"
      - id: "1.2"
        text: "Смартфон"
      - id: "1.3"
        text: "Персональный компьютер, ноутбук"
      - id: "1.4"
        text: "Планшет"
      - id: "1.5"
        text: "Мессенджеры"
      - id: "1.6"
        text: "Социальные сети"
      - id: "1.7"
        text: "Telegram-каналы"
      - id: "1.8"
        text: "Приложение VK"
      - id: "1.9"
        text: "Бесплатные мобильные приложения"
      - id: "1.10"
        text: "Платные мобильные приложения"

  - question_id: "q2"
    text: "Оцените свою готовность пользоваться различными цифровыми возможностями в перспективе ближайших 5 лет"
    type: "multi-choice"
    options:
      - id: "2.1"
        text: "Готов пользоваться беспилотным транспортом"
      - id: "2.2"
        text: "Готов получать посылки с помощью дронов или роботов"
      - id: "2.3"
        text: "Готов внедрить нейро-импланты по рекомендации врача"
      - id: "2.4"
        text: "Готов использовать умную колонку как ассистента"
      - id: "2.5"
        text: "Готов к рекомендациям чат-ботов для самообучения"
      - id: "2.6"
        text: "Готов к переходу профессий в виртуальный формат"
      - id: "2.7"
        text: "Готов ориентироваться на ИИ при постановке диагнозов"
      - id: "2.8"
        text: "Готов закупать электроэнергию или участвовать в её производстве"
      - id: "2.9"
        text: "Готов участвовать в контроле контента на основе блокчейна"
      - id: "2.10"
        text: "Готов к внедрению умных устройств по всему городу"
      - id: "2.11"
        text: "Готов иметь цифровые финансовые активы в токенах"
      - id: "2.12"
        text: "Готов к технологиям дополненной реальности"
      - id: "2.13"
        text: "Готов к использованию ИИ для управления проектами"

  - question_id: "q3"
    text: "Выберите утверждения о чертах цифрового поведения, с которыми Вы согласны"
    type: "multi-choice"
    options:
      - id: "3.1"
        text: "Цифровые технологии поднимают настроение"
      - id: "3.2"
        text: "Готов довериться ИИ в повседневных задачах"
      - id: "3.3"
        text: "Недостоверная информация в сети ведёт к антисоциальным действиям"
      - id: "3.4"
        text: "Цифровые сервисы побуждают к благотворительности"
      - id: "3.5"
        text: "Много времени в соцсетях формирует зависимость"
      - id: "3.6"
        text: "В интернете можно получить поддержку"
      - id: "3.7"
        text: "Считаю себя активным пользователем интернета"
      - id: "3.8"
        text: "Негативные новости вводят в апатию и депрессию"
      - id: "3.9"
        text: "В онлайн-пространстве невозможно избежать давления"
      - id: "3.10"
        text: "Социальный рейтинг позволит безопаснее взаимодействовать"
      - id: "3.11"
        text: "Цифровые технологии могут изменить жизнь к лучшему"
      - id: "3.12"
        text: "Часто получаю услуги через интернет"
      - id: "3.13"
        text: "Люблю потреблять цифровой контент"
      - id: "3.14"
        text: "Роботы-полицейские сделали бы города безопаснее"
      - id: "3.15"
        text: "Полезно приобрести ценные бумаги по рекомендации ИИ"

  - question_id: "q4"
    text: "Какие трудности Вы испытываете при использовании сервисов и приложений"
    type: "multi-choice"
    options:
      - id: "4.1"
        text: "Сложности поиска подходящего сервиса"
      - id: "4.2"
        text: "Нет необходимых навыков для работы в сети"
      - id: "4.3"
        text: "Много действий для скачивания приложения"
      - id: "4.4"
        text: "Тяжёлое привыкание к новому интерфейсу"
      - id: "4.5"
        text: "Медленная адаптация к новым технологиям"
      - id: "4.6"
        text: "Не решены вопросы защиты данных"
      - id: "4.7"
        text: "Слишком много рисков без этического кодекса"
      - id: "4.8"
        text: "Усиленная пропаганда положительных сторон технологий"
      - id: "4.9"
        text: "Отсутствует предупреждение ошибок технологий"
